### PR TITLE
Add gitpod config

### PR DESCRIPTION
**Pull request by shihabmridha**
this commit adds support for Gitpod.io, a free automated
dev environment that makes contributing and generally working on GitHub
projects much easier. It allows anyone to start a ready-to-code dev
environment for any branch, issue and pull request with a single click.

### CODE REVIEW

**Comment by devKshitijJain** [comment]
@shihabmridha are you going to merge this?

**Comment by shihabmridha** [comment]
Probably not. I was experimenting.

**Comment by devKshitijJain** [comment]
Okay

**Comment by sravan008** [comment]
C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:794
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: 'C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\config\default.json': SyntaxError: Unexpected number in JSON at position 65
    at Config.util.parseFile (C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:794:11)
    at C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:601:26
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:600:16)
    at new Config (C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (C:\Users\GodMe\Desktop\try\eduactive\educative.io-downloader\node_modules\config\lib\config.js:1436:31)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)

**Pull request closed without merging**
